setwd("C:/Users/Giuseppe/Documents/.magistrale/secondo anno/AppStat/Exams/2023/20230207/20230207")
library(mvtnorm) # to deal with multivariate normal distributions
library(car) # "Companion to Applied Regression" for regression analysis


data <- read.table('decathlon.txt', header=T)

head(data)
dim(data)

n <- dim(data)[1]
p <- dim(data)[2]


# if there are labels (two in this case), skip otherwise
{
  # store them and remove from data
  data.label <- data[, 1:2]
  data       <- data[, -(1:2)]
}
# even before boxplots we can already assume that variability will be different 
# for different features. 
# Variability of times in 1500m will be grater than variability in 100m (range from
# 9.5 to 11 seconds).  
# For the meters measurment, there are different sports.


# Indeed:

boxplot(scale(x = data, center = T, scale = F), las = 2, col = 'gold')


# transformation to have all variables denoting better performance for higher values
# transform the seconds in 1/seconds, while meters are untouched
colnames(data)

data$X100m = 1/data$X100m
data$X400m <- 1/data$X400m
data$X110m_hurdles <- 1/data$X110m_hurdles
data$X1500m <- 1/data$X1500m

boxplot(scale(x = data, center = T, scale = F), las = 2, col = 'gold')


{
  data.sd <- scale(data)
  data.sd <- data.frame(data.sd)
  head(data.sd)
  # Boxplot
  par(mfrow = c(1, 1))
  boxplot(data.sd, las = 2, col = 'gold')
  # now every box has similar height
  # you can see in the next plot how every feature has variance 1
  barplot(sapply(data.sd, sd)^2, las = 2, main = 'Standardized Variables', ylim = c(0, 7),
          ylab = 'Variances')
}


# PCA
{ 
  pc.data <- princomp(data.sd, scores = T)
  pc.data
  summary(pc.data)
}

# Loadings
{
  load.data <- pc.data$loadings
  
  load.data[,1]
  
  # Graphical representation of loadings of the first 3 PC
  par(mar = c(2,2,2,1), mfrow=c(3,1))
  for(i in 1:3)barplot(load.data[,i], ylim = c(-1, 1), main=paste('Loadings PC ',i,sep=''))
  
  # interpretation: say that the second component has high loadings for 4/5 stars
  #                                                and negative loading for 1/2 stars
  #                 -> an high second component indicates high flow(night spent) for expensive solutions 
  #                 -> a low second component indicates high flow(night spent) for cheap solutions
  # go to CASE 1 for further interpretations
  
  # first component -> atlets performing good on running disciplines (mostly) and long jump
  #                    -> indicates atlets with well trained legs
  # second component -> penalize atlets of throws disciplines
  # third component is trying to capture what was left by first teo components
  
}
par(mfrow=c(1,1))
# biplot, visualize projection on the space generated by the first 2 principal components
biplot(pc.data)


# to have high score of both the first 2 PC, the atlets must perform good in resistant (1500)
# being discrete in other types of run and don't excel in throws
biplot(pc.data, choices=c(2,3))
# to have also second and third component high, must excel in 1500m and 100m too
# or be very very good in 400m



{
  par(mfrow = c(1, 1))
  plot(pc.data, las = 2, main = 'Principal Components', ylim = c(0, 7))
  abline(h=1, col = "blue", lty = 2)
}
# by taking first three components 
# we also explain 70% of the varaibility of the dataset and we still have easy interpretation

# Cum variance:
# 0.3514926 0.5485433 0.7033151

new_entry <- data.frame(
X100m   = 1/10.81,
long_jump=    7.46,
shot_put=    14.56,
high_jump=   2.02,
X400m  = 1/ 47.90,
X110m_hurdles =  1/14.44,
discus_throw = 43.04,
pole_vault =  4.90,
javelin_throw =  57.24,
X1500m = 1/(4*60 + 41.63))

x.mean = colMeans(data)
x.cov = sapply(data, FUN = sd)

new_entry = (new_entry - x.mean)/ x.cov

new_entry_projected <- predict(pc.data, newdata = new_entry)[, 1:3]  
new_entry_projected
scores.data <- pc.data$scores
new_entry_projected












