setwd("C:/Users/Giuseppe/Documents/.magistrale/secondo anno/AppStat/Exams/2023/20230707/20230707")
library(mvtnorm) # to deal with multivariate normal distributions
library(car) # "Companion to Applied Regression" for regression analysis


data <- read.table('products.txt', header=T)
head(data)

dim(data)

n <- dim(data)[1]
p <- dim(data)[2]
pairs(data, pch=19)


# Some of them are correlated: oven and fridge
#                             dishwasher and oven and television

par(mfrow = c(1,1))
## centred boxplot
boxplot(scale(x = data, center = T, scale = F), las = 2, col = 'gold')

# We can use the original variables since the variances are comparable 

pc.data <- princomp(data, scores = T)
pc.data
summary(pc.data)

# to explain at least 80% of the variance we must take at least the first
# 5 components
par(mfrow = c(1, 1))
plot(cumsum(pc.data$sde^2) / sum(pc.data$sde^2), type = 'b', axes = TRUE, 
     xlab = 'Number of components', ylab = 'Contribution to the total variance', ylim = c(0, 1))
abline(h = 1, col = 'blue')
abline(h = 0.8, lty = 2, col = 'blue')

#There isn't a clear number of components to take, since there isn't an elbow
# The best strategy here is to fix a threshold to explain the variance and 
# take that amount of components

# b) graphical representation of the loadings of the first three principal components
par(mfrow = c(3,1))
for(i in 1:3) barplot(load.data[,i], ylim = c(-1, 1))
# First component: contrast between assortment of electrodomestics and portable
# devices

# c) 
par(mfrow = c(1,1))
# biplot, visualize projection on the space generated by the first 2 principal components
biplot(pc.data)

# The second component is a general indicator of the assortments
# the 134-th product has both PC low
# -> may be a shop that contains fewer products than other shops of the dataset
#     and that contains fewer portable devices in favor of electrodomestic
# We see that:
data[134, ]
# -> all degrees of importance for portable device is low


# d)
## if he asks to project a new entry to the space generated by the first k component:
new_entry <- data.frame(
  cellphone = 1.41,
  tablet = 1.14,
  smartwatch  =1.02,
  computer     = 1.21,
  drone = 1.11,
  dockstation    = 1.14,
  fridge = 0.99,
  oven = 0.73,
  dishwasher = .94,
  television = 1.04,
  blender = 1.02,
  hairdryer = 1.11
)
new_entry_projected <- predict(pc.data, newdata = new_entry)[, 1:5]

new_entry_projected


