###------------------------------###
### PRINCIPAL COMPONENT ANALYSIS ###-------------------------------------------
###------------------------------###

### Try It Out! ###
rm(list = ls())
graphics.off()
par(mfrow=c(1,1))
cat("\014")
data <- read.table('datasets/data_pca.txt', header = T)
data.label <- data[, 9]
data <- data[, 1:8]
### Try It Out! ###

boxplot(data, las = 2, col = 'gold')
boxplot(scale(x = data, center = T, scale = F), las = 2, col = 'gold')
boxplot(scale(x = data, center = T, scale = T), las = 2, col = 'gold')


#### PCA on Original Data -----

pc.data <- princomp(data, scores = T)
pc.data
summary(pc.data)

layout(matrix(c(2, 3, 1, 3), 2, byrow = TRUE))

plot(pc.data, las = 2, main = 'Principal Components', ylim = c(0, 7))
abline(h = 1, col = 'blue')

barplot(sapply(data, sd)^2, las = 2, main = 'Original Variables', ylim = c(0, 7),
        ylab = 'Variances')

plot(cumsum(pc.data$sde^2) / sum(pc.data$sde^2), type = 'b', axes = FALSE, 
     xlab = 'Number of components', ylab = 'Contribution to the total variance', ylim = c(0, 1))
abline(h = 1, col = 'blue')
abline(h = 0.8, lty = 2, col = 'blue')
box()
axis(2, at = 0:10/10, labels = 0:10/10)
axis(1, at = 1:ncol(data), labels = 1:ncol(data), las = 2)


#### PCA on Standardized Variables -----

data.sd <- scale(data)
data.sd <- data.frame(data.sd)

boxplot(data.sd, las = 2, col = 'gold')

pc.data <- princomp(data.sd, scores = T)
pc.data
summary(pc.data)

layout(matrix(c(2, 3, 1, 3), 2, byrow = TRUE))

plot(pc.data, las = 2, main = 'Principal Components', ylim = c(0, 7))
abline(h = 1, col = 'blue')

barplot(sapply(data.sd, sd)^2, las = 2, main = 'Original Variables', ylim = c(0, 7),
        ylab = 'Variances')

plot(cumsum(pc.data$sde^2) / sum(pc.data$sde^2), type = 'b', axes = FALSE, 
     xlab = 'Number of components', ylab = 'Contribution to the total variance', ylim = c(0, 1))
abline(h = 1, col = 'blue')
abline(h = 0.8, lty = 2, col = 'blue')
box()
axis(2, at = 0:10/10, labels = 0:10/10)
axis(1, at = 1:ncol(data.sd), labels = 1:ncol(data.sd), las = 2)


#### Variances ----

pc.data$sdev^2

# Proportion of variance explained by component 1
var(as.matrix(data.sd) %*% pc.data$loadings[, 1]) / sum(sapply(data.sd, var))


#### Loadings ----

load.data <- pc.data$loadings
load.data

nPCs <- 3
par(mar = c(2,2,2,1), mfrow = c(nPCs, 1))
for(i in 1:nPCs) barplot(load.data[, i], ylim = c(-1, 1), main = paste('Loadings PC ', i, sep = ''))

# The first PC represents...
# The second PC contains the information...

# High PC1: big...
# Low PC1: small...
# High PC2: high..., low...
# Low PC2: small..., high...


#### Scores ----

scores.data <- pc.data$scores

col.lab <- ifelse(data.label[] %in% c("class2_name", "class3_name"), 
                  ifelse(data.label[] %in% c("class3_name"), 
                         'blue', 'green'), 
                  'red')

par(mfrow = c(1, 1))
plot(scores.data[, 1:2], col = col.lab, pch = 19, 
     xlim = c(min(scores.data[, 1]) - 1, max(scores.data[, 1]) + 1), 
     ylim = c(min(scores.data[, 2]) - 1, max(scores.data[, 2]) + 1))
abline(h = min(scores.data[, 2]) - 1, v = min(scores.data[, 1]) - 1, col = 1)
points(scores.data[, 1], rep(min(scores.data[, 2]) - 1, dim(data)[1]), col = col.lab, pch = 19)
points(rep(min(scores.data[, 1]) - 1, dim(data)[1]), scores.data[, 2], col = col.lab, pch = 19)
abline(h = 0, v = 0, lty = 2, col = 'grey')
legend('topright', levels(factor(data.label[])), fill = c('red', 'green', 'blue'), bty = 'n')

biplot(pc.data)
biplot(pc.data, choices = 1:2)


#### Projections on PC Space ----

##### PCA Being Performed on Original Data -----

# Projection on the space generated by the k-th principal component
par(mfrow = c(2, 5))
matplot(t(data), type = 'l', main = 'Data', ylim = range(data))
meanA <- colMeans(data)
matplot(meanA, type = 'l', main = '0 PC', lwd = 2, ylim = range(data))
for(i in 1:8)
{
  projection <- matrix(meanA, dim(data)[[1]], dim(data)[[2]], byrow = T) + scores.data[, i] %*% t(load.data[, i])
  matplot(t(projection), type='l', main = paste(i, 'PC'), ylim = range(data))
  matplot(meanA, type='l', lwd = 2, add = T)
}

# Projection on the space generated by the first k principal components
par(mfrow = c(2, 5))
matplot(t(data), type = 'l', main = 'Data', ylim = range(data))
meanF <- colMeans(data)
matplot(meanF, type = 'l', main = 'First 0 PCs', lwd = 2, ylim = range(data))
projection <- matrix(meanF, dim(data)[[1]], dim(data)[[2]], byrow = T)
for (i in 1:8) {
  projection <- projection + scores.data[, i] %*% t(load.data[, i])
  matplot(t(projection), type = 'l', main = paste('First', i, 'PCs'), ylim = range(data))
  matplot(meanF, type = 'l', lwd = 2, add = T)
}


##### PCA Being Performed on Standardized Variables -----

# Projection on the space generated by the k-th principal component
par(mfrow = c(2, 5))
matplot(t(data.sd), type = 'l', main = 'Data', ylim = range(data.sd))
meanA <- colMeans(data.sd)
matplot(meanA, type = 'l', main = '0 PC', lwd = 2, ylim = range(data.sd))
for(i in 1:8)
{
  projection <- matrix(meanA, dim(data.sd)[[1]], dim(data.sd)[[2]], byrow = T) + scores.data[, i] %*% t(load.data[, i])
  matplot(t(projection), type='l', main = paste(i, 'PC'), ylim = range(data.sd))
  matplot(meanA, type='l', lwd = 2, add = T)
}

# Projection on the space generated by the first k principal components
par(mfrow = c(2, 5))
matplot(t(data.sd), type = 'l', main = 'Data', ylim = range(data.sd))
meanF <- colMeans(data.sd)
matplot(meanF, type = 'l', main = 'First 0 PCs', lwd = 2, ylim = range(data.sd))
projection <- matrix(meanF, dim(data.sd)[[1]], dim(data.sd)[[2]], byrow = T)
for (i in 1:8) {
  projection <- projection + scores.data[, i] %*% t(load.data[, i])
  matplot(t(projection), type = 'l', main = paste('First', i, 'PCs'), ylim = range(data.sd))
  matplot(meanF, type = 'l', lwd = 2, add = T)
}


##### Projection of a New Datum -----

new.datum <- c(37548.50, 754.42, 318.34, 154.25, 0.88, 37506.40, 219.63, 0.80)

###### PCA Being Performed on Original Data ------

new.datum.score <- t(load.data) %*% (new.datum - colMeans(data))
new.datum.score

plot(pc.data$scores[, 1:2], pch = 19, las = 2)
points(new.datum.score[1], new.datum.score[2], col = 'red', pch = 19)


###### PCA Being Performed on Standardized Variables ------

new.datum.std <- (new.datum - colMeans(data)) / sapply(data, sd)

new.datum.std.score <- t(load.data) %*% (new.datum.std - colMeans(data.sd))
new.datum.std.score

plot(pc.data$scores[, 1:2], pch = 19, las = 2)
points(new.datum.std.score[1], new.datum.std.score[2], col = 'red', pch = 19)