###----------------------###
### Problem 1 (20240613) ###
###----------------------###

library(MVN)
library(mvtnorm)
library(car)

rm(list = ls())
graphics.off()

data <- read.table('whisky.txt', header = T)
head(data)


# a) ----------------------------------------------------------------------

mvn(data)$multivariateNormality$'p value'
# 0.1615312

M <- sapply(data, mean)
S <- cov(data)

set.seed(20240613)
X <- rmvnorm(n = 10000, mean = M, sigma = S)
head(X)

for(i in 1:dim(data)[1])
{
  print(paste("Data element #", i, ": ", sep = ''))
  print(data[i, ])
  print("Various randomly generated elements with a similar first variable:")
  print(X[X[, 1] >= (data[i, 1] - 0.1) & X[, 1] <= (data[i, 1] + 0.1), ])
}
# It seems like the rows of the data matrix have been independently generated by the same tri-variate Gaussian distribution


# b) ----------------------------------------------------------------------

n <- dim(data)[1]
q <- dim(data)[2]

C <- matrix(c(-1, 1, 0,
              -1, 0, 1), q-1, q, byrow = T)
C

alpha <- .05
delta.0 <- c(0, 0)

Md <- C %*% M 
Sd <- C %*% S %*% t(C) 
Sdinv <- solve(Sd)

T2 <- n * t(Md - delta.0) %*% Sdinv %*% (Md - delta.0)
cfr.fisher <- ((q - 1) * (n - 1) / (n - (q - 1))) * qf(1 - alpha, (q - 1), n - (q - 1)) 

T2 < cfr.fisher
# Yes, there's a taster which over/under-prices the bottles compared to the two others

P <- 1 - pf(T2 * (n - (q - 1)) / ((q - 1) * (n - 1)), (q - 1), n - (q - 1))
P
# 0.006252078


# c) ----------------------------------------------------------------------

diff <- cbind(data[, 2] - data[, 1], data[, 3] - data[, 1])

plot(diff[, 1], diff[, 2], asp = 1, pch = 19, xlim = c(-20, 20))
points(colMeans(diff)[1], colMeans(diff)[2], col = 'red', pch = 9, cex = 1)

ellipse(center = c(Md), shape = Sd/n, radius = sqrt(cfr.fisher), lwd = 2, col = 'grey', center.cex = 1.25)
abline(h = 0)
abline(v = 0)


# d) ----------------------------------------------------------------------

k <- q-1   # number of increments (i.e., dim(C)[1])
cfr.t <- qt(1 - alpha/(2*k), n-1)

BF.I <- cbind(Md - cfr.t * sqrt(diag(Sd)/n),
              Md,
              Md + cfr.t * sqrt(diag(Sd)/n))
dimnames(BF.I)[[2]] <- c('inf', 'center', 'sup')
dimnames(BF.I)[[1]] <- c('t1-t2', 't1-t3')
BF.I
#              inf center       sup
# t1-t2  -5.819742     -1  3.819742
# t1-t3 -13.730819     -8 -2.269181


# Extra -------------------------------------------------------------------

pdf(file = "CR.pdf", onefile = T)

plot(diff[, 1], diff[, 2], asp = 1, pch = 19, xlim = c(-20, 20))
points(colMeans(diff)[1], colMeans(diff)[2], col = 'red', pch = 9, cex = 1)

ellipse(center = c(Md), shape = Sd/n, radius = sqrt(cfr.fisher), lwd = 2, col = 'grey', center.cex = 1.25)
abline(h = 0)
abline(v = 0)

dev.off()

