library(mvtnorm) # to deal with multivariate normal distributions
library(car) # "Companion to Applied Regression" for regression analysis
setwd("C:/Users/Giuseppe/Documents/.magistrale/secondo anno/AppStat/Exams/2020/20200907/20200907")

data <- read.table('weather.txt', header=T)

head(data)
dim(data)

n <- dim(data)[1]
p <- dim(data)[2]




# see if the variances are different
{
  par(mfrow = c(1,1))
  boxplot(data, las = 2, col = 'gold')
  ## centred boxplot
  boxplot(scale(x = data, center = T, scale = F), las = 2, col = 'gold')
# we need standardization: humidity will masks visibility and meanwind otherwise
}

{
  data.sd <- scale(data)
  data.sd <- data.frame(data.sd)
  head(data.sd)
  # Boxplot
  par(mfrow = c(1, 1))
  boxplot(data.sd, las = 2, col = 'gold')
  # now every box has similar height
  # you can see in the next plot how every feature has variance 1
  barplot(sapply(data.sd, sd)^2, las = 2, main = 'Standardized Variables', ylim = c(0, 7),
          ylab = 'Variances')
}

# PCA
{ 
  pc.data <- princomp(data.sd, scores = T)
  pc.data
  summary(pc.data)
}
Loadings
{
  load.data <- pc.data$loadings
  
  
  # Graphical representation of loadings of the first 3 PC
  par(mar = c(2,2,2,1), mfrow=c(3,1))
  for(i in 1:3)barplot(load.data[,i], ylim = c(-1, 1), main=paste('Loadings PC ',i,sep=''))
  
  # PC1 is a weighted average of temperatures (°C) and accounting also for visibility:
  #       high PC1 indicates high temperature and dew, and a good visibility
  # high PC2 indicates measurments with low amount of wind
  # PC3 is a contrast between humidity (combined with dew) and visibility:
  #       -> is high when there is a lot of humidity and dew and there is low visibility
}
par(mfrow=c(1,1))
biplot(pc.data)

# on 4-th quadrant there are observations with high PC1 but low PC2:
# -> days with high temperatures and low amount of wind


# We see on first quadrants days from 100-200 -th of the years
# that are indeed from april to june/july : is reasonable to say that in those days there are high temp
# and no wind

# there are other points on 4-th qudrants of those days: windy days but high temperature
# (for instance 185, 195) that are in june. May be related to the tempeste estive of the first day of the summer

# first day of the years (7-8-9 and so on, in jan/feb) have all high humidity
# low PC1 (so temperature), and no wind


# d
par(mfrow = c(1, 1))
plot(pc.data, las = 2, main = 'Principal Components', ylim = c(0, 7))
abline(h=1, col = "blue", lty = 2)
# we take first 3 component (we see from summary that explain 94% of variability)

# all original features were explaining 1 variability (since standardized)
# -> I'm doing better with PC than with original variables, they explain more than 1 std

# Variance explained along first 3 PC
# 0.529159 0.7642134 0.9407453 


# Project a new entry to the space generated by the first 3 component:
{
  new_entry <- data.frame(
    MeanTemp      = 30,
    MinTemp = 23,
    MaxTemp = 26,
    DewPoint = 22,
    Humidity = 65.,
    Visibility = 19 , 
    MeanWind  = 5 ,
    MaxWind = 15
    # ... 
  )
  x.mean = colMeans(data)
  x.cov = sapply(data, FUN = sd)
  
  new_entry = (new_entry - x.mean)/ x.cov
  
  new_entry_projected <- predict(pc.data, newdata = new_entry)[, 1:3]  
  new_entry_projected
  
  # Comp.1    Comp.2    Comp.3 
  # 2.9915433 0.7227603 0.9023651 
}


